export const ITEMS_TO_ACTIVATE_BOTH_DOTTS = 3;
export const BOUNDARY_OF_NORMAL_PAGINATION = 4;
export const ITEMS_TO_DISPLAY_WHEN_IN_MIDDLE = 3;

// ITEMS_TO_DISPLAY_WHEN_IN_MIDDLE cannot be higher than ITEMS_TO_ACTIVATE_BOTH_DOTTS!

// ITEMS_TO_DISPLAY_WHEN_IN_MIDDLE will display 2*(ITEMS_TO_DISPLAY_WHEN_IN_MIDDLE - 1) + 1 items!
